### PR TITLE
Pull dev into master

### PR DESCRIPTION
**Pull request by teunbrand**

### CODE REVIEW

**Comment by teunbrand** [comment]
TODO: Check visualise 4C output, there was a merge conflict about this

**Comment by teunbrand** [comment]
Seems like it fails to make the vignette. @robinweide when you have the time, could you take a gander at what might be going wrong with the vignette?

**Comment by robinweide** [comment]
Please add this to your travil.yaml (see master):

`r_check_args: "--no-vignettes"`

**Comment by robinweide** [comment]
Added biocStyle: https://github.com/robinweide/GENOVA/commit/0de32f5b55e5b26e366b1e0c692837a565dfd361

**Comment by robinweide** [comment]
Disabled vignette building in 3c7a99a and 4bbef5e.

**Pull request merged**
